### get items
GET http://localhost:4004/odata/v4/service/items/Items
Content-Type: application/json
Accept: application/json


### Test filterItems Function
GET http://localhost:4004/odata/v4/service/items/filterItems?quantity=10
Content-Type: application/json
Accept: application/json

 
### Test createItem Action - Valid Quantity
POST http://localhost:4004/odata/v4/service/items/createItem
Content-Type: application/json
Accept: application/json

{
    "title": "Sample Item",
    "quantity": 40
}

###

### Test createItem Action - Quantity Greater than 100 (Should Return Error)
POST http://localhost:4004/odata/v4/service/items/createItem
Content-Type: application/json
Accept: application/json

{
    "title": "Invalid Quantity",
    "quantity": 150
}

###
